name: Build & Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - contents-update
      - contents-issues-update
  push:
    branches:
      - v4
    tags:
      - "v*"

concurrency:
  group: "build"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Contents
        uses: actions/checkout@v3
        with:
          repository: Yixuan-Wang/blog-contents
          ref: v4
          path: data

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup `pnpm`
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache `pnpm` Modules
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node Packages
        run: pnpm install

      - name: Build
        env:
          PUBLIC_BUILD_SITE_URL: "https://blog.yixuan-wang.site"
          PUBLIC_BUILD_BASE_URL: "/"
          PUBLIC_BUILT_BY: "ci"
          POSTS_DIR: "data/posts"
          GITHUB_USER: "Yixuan-Wang"
          GITHUB_REPO: "blog-contents"
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: pnpm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: blog-build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Donwload Artifact
        uses: actions/download-artifact@v3
        with:
          name: blog-build
          path: ./dist

      - name: Deploy Server
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: dist/.
          remote_path: ${{ secrets.MIRROR_TARGET }}
          remote_host: ${{ secrets.MIRROR_HOST }}
          remote_user: github
          remote_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
