name: "Gatsby Build & Publish"

on:
  push:
    branches: [ master ]

  workflow_dispatch:

  repository_dispatch: 
    types: [contents-issues-update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node Modules
        uses: actions/cache@v2
        id: cache-node
        with:
          path: |
            **/node_modules
          key: node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-

#       - name: Cache Gatsby Files;
#         uses: actions/cache@v2
#         id: cache-gatsby
#         with:
#           path: |
#             .cache
#             public
#           key: gatsby-${{ hashFiles('package-lock.json', 'gatsby-*.js') }}
#           restore-keys: |
#             gatsby-

      - name: Install Node Modules
        run: SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn

      - name: Create Env
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          touch .env
          echo ACCESS_TOKEN=$ACCESS_TOKEN > .env

      - name: Gatsby Build
        run: yarn build --prefix-paths

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

  mirror:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Sync to Gitee
        uses: spyoungtech/mirror-action@master
        with:
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          REMOTE: "ssh://git@gitee.com:yixuan-wang/blog.git"
          GIT_SSH_NO_VERIFY_HOST: "true"

      - name: Deploy Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          gitee-username: yixuan-wang
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: yixuan-wang/blog
          branch: gh-pages      
